name: WakeUpStreamlit

on:
  schedule:
    # Запуск каждые 30 минут (оптимально для поддержания активности)
    - cron: '*/30 * * * *'
  workflow_dispatch: # Оставляем ручной запуск

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send realistic request to app
        run: |
          curl -I -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://workout-app-o8dt87vxa4t4a8nsr49oc3.streamlit.app/
